name: eslint
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - run: npx install --dev eslint-config-airbnb
    - run: npx install --dev eslint-plugin-import
    - run: npx install --dev eslint-plugin-jsx-a11y
    - run: npx install --dev eslint-plugin-react
    - run: npx install --dev eslint-plugin-react-hooks
    - run: npx install --dev eslint-plugin-react-native
    - run: npx eslint .
