name: eslint
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - run: npx install-peerdeps --dev eslint-config-airbnb
    - run: npx eslint .
